import Head from 'next/head'

export const getServerSideProps = async () => {
  const response = await fetch('http://localhost:5000/posts/')
  const data = await response.json()
  return {
    props: {
      data: data
    }
  }
}

export default function Home() {
  return (
    <div className='flex items-center justify-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-4/5'>
        <h1 className='my-8 px-8 py-4 rounded-xl text-3xl text-center' style={{ boxShadow: '0px 5px 15px -5px #b0b0b0' }}>Next.js & Nest.js Blog</h1>
      </main>

    </div>
  )
}
