import Head from 'next/head'
import React from 'react'
import { PostType } from '../../src/types/PostType'
import { GetServerSideProps } from 'next'

interface PostPageProps {
  data: PostType
}

export const getServerSideProps: GetServerSideProps<PostPageProps> = async ({ params }) => {
  const { id } = params as { id: string }
  const response = await fetch(`http://localhost:5000/posts/${id}`)
  const data = await response.json()
  return {
    props: {
      data: data
    }
  }
}

export default function Post({ data }: PostPageProps) {
  return (
    <div className='flex items-center justify-center h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-2/5'>
      </main>
    </div>
  )
}
