import Head from 'next/head'
import React from 'react'

export default function Post() {
  return (
    <div className='flex items-center justify-center h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-2/5'>
      </main>
    </div>
  )
}
